driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/student_manager?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
username=root
password=qwertYUIOP200512
redis.host=localhost
redis.port=6379
redis.password=
redis.database=0
redis.timeout=2000
